### PR TITLE
Add Node.js 14 as hidden and in preview

### PR DESCRIPTION
**Pull request by mhoeger**
@pragnagopa for review

### CODE REVIEW

**Comment by pragnagopa** [comment]
cc @Francisco-Gamino - for powershell cmdlets

**Review by pragnagopa — APPROVED** [review]

**Comment by pragnagopa** [comment]
@mhoeger - please open or link issues from Az CLI , Powershell Cmdlets and VS Code here

**Comment by pragnagopa** [comment]
cc @EricJizbaMSFT  for VS Code changes as fyi - We are adding support for Node 14 with `hidden` flag set to true as backend changes are still rolling out.

**Comment by mhoeger** [comment]
Items for tooling updates:
VS Code: https://github.com/microsoft/vscode-azurefunctions/issues/2385
Az CLI: https://github.com/Azure/azure-cli/issues/15407 and https://github.com/Azure/Azure-Functions/issues/1719
PowerShell: https://github.com/Azure/azure-powershell/issues/13149

**Pull request merged**
